version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: hapi_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hapi_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hapi_rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Web management panel http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: hapi_adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmq_data: